# Generated by Django 4.0.1 on 2022-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('priority', '-completed')},
        ),
    ]
