# Generated by Django 4.0.1 on 2022-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_userreportconfiguration_dispatch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreportconfiguration',
            name='last_dispatched',
            field=models.DateTimeField(null=True),
        ),
    ]
