# Generated by Django 4.0.1 on 2022-02-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('completed', 'priority')},
        ),
    ]
