# Generated by Django 4.0.1 on 2022-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_userreportconfiguration_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreportconfiguration',
            name='dispatch_time',
            field=models.TimeField(null=True),
        ),
    ]
