# Generated by Django 4.0.1 on 2022-02-27 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_userreportconfiguration_last_dispatched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreportconfiguration',
            name='dispatch_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userreportconfiguration',
            name='last_dispatched',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
